services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ff15
      POSTGRES_DB: taarf
    ports:
      - "5433:5432"

    volumes:
    - db_data:/var/lib/postgresql/data  

volumes:
  db_data:  